# Generated by Django 2.2.26 on 2022-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0029_auto_20210202_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorWCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('username', models.CharField(help_text='Username pour la connexion à WCA', max_length=128, verbose_name='Username')),
                ('password', models.CharField(help_text='Mot de passe pour la connexion à WCA', max_length=128, verbose_name='Mot de passe')),
                ('url_authentic', models.URLField(default='https://agents.wallonie-connect.be/', help_text='URL de de base de connexion à authentic\nExemple https://agents.wallonie-connect.be/', verbose_name='URL authentic')),
                ('users', models.ManyToManyField(blank=True, related_name='_connectorwca_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Connecteur pour WCA',
            },
        ),
    ]
