# Generated by Django 2.2.26 on 2022-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_wca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorwca',
            name='url_authentic',
            field=models.URLField(default='https://agents.wallonie-connect.be/', help_text='URL de de base de connexion à authentic\nExemple https://agents.wallonie-connect.be/', verbose_name='URL authentic'),
        ),
        migrations.AlterField(
            model_name='connectorwca',
            name='password',
            field=models.CharField(help_text='Mot de passe pour la connexion à WCA', max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='connectorwca',
            name='username',
            field=models.CharField(help_text='Username pour la connexion à WCA', max_length=128, verbose_name='Username'),
        ),
    ]
